name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set cache key
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV

      - name: Cache pip and .cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            .cache
          key: mkdocs-${{ runner.os }}-${{ env.cache_id }}
          restore-keys: |
            mkdocs-${{ runner.os }}-

      - name: Install dependencies
        run: pip install mkdocs-material "mkdocstrings[python]"

      - name: Deploy with MkDocs
        run: mkdocs gh-deploy --force
