name: Publish Python 🐍 Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  realease-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package (wheel + sdist)
        run: |
          cd src
          python -m build --sdist --wheel --outdir dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TWINE_PASSWORD }}
